### ISSUE TITLE
为什么不考虑用Docker镜像的方式发布部署方案呢

### ISSUE THREAD

**Issue by ckeyer** [mogutt/TTAutoDeploy#11]

**Comment by bluefoxah** [comment]
非常感谢您的意见，目前我们在docker这块不是很熟，后期如有可能我们会考虑的，也欢迎对这块很熟的人给我们提供一些帮助。

**Comment by xujialiang** [comment]
一直想有人提供一个镜像~~~~不管是vm  还是docker~~唉。。。。不喜折腾~~~~~

**Comment by purplegrape** [comment]
问下bluefox，TT支持在debian wheezy下安装吗，我可以考虑打包一个容器镜像出来，但是TT安装不熟悉。
