### ISSUE TITLE
这个项目完全不可用,完全是浪费别人的时间

### ISSUE THREAD

**Issue by undeadking** [mogutt/TTAutoDeploy#3]
问题太多了,花了两个半小时处理,到im_server这一步放弃,看了一下setup.sh脚本内容,不太认为能跑起来

- 编译redis时报错

- percona的下载地址过期,需要手工修正

- percona在内存小的机器上无法启动

- php在内存小的机器上无法编译

- jdk需要自己下载,在readme中未提及

- im_web缺少zip文件,需要自己去 https://github.com/mogutt/TTPHPServer 下载

- im_server缺少tar.gz文件,对应的项目应该是TTServer

部分解决问题的链接:

http://www.webtrafficexchange.com/solved-mysql-crash-fatal-error-cannot-allocate-memory-buffer-pool

http://unix.stackexchange.com/questions/94479/jemalloc-and-other-errors-making-redis-on-centos-6-4

http://nbaiwan.blog.51cto.com/6286161/1425200

**Comment by cryfish** [comment]
TT的架构还是不错的,提个建议,iOS和安卓的客户端对于协议的收发处理代码太麻烦了.建议改成block作为参数的回调机制,这样收发一个包只用一个函数就搞定,不用再写一个api的类去封装一大堆了
